services:
  squid:
    # build image from Dockerfile
    build: .
    container_name: squid
    ports:
      - "3128:3128"
      - "3129:3129"
    environment:
      - TZ=UTC
    volumes:
      - $BD/logs:/var/log/squid
      - $BD/data:/var/spool/squid
      - $BD/config:/etc/squid
    networks:
      proxy1:
        ipv4_address: 10.5.0.2
      proxy2:
        ipv4_address: 10.5.1.2
      proxy3:
        ipv4_address: 10.5.2.2

  caddy1:
    image: caddy:latest
    container_name: caddy1
    ports:
      - "8081:80"
    volumes:
      - $PWD/caddy-conf/cnf-1:/etc/caddy
    networks:
      proxy1:
        ipv4_address: 10.5.0.3
      proxy2:
        ipv4_address: 10.5.1.3
      proxy3:
        ipv4_address: 10.5.2.3

  caddy2:
    image: caddy:latest
    container_name: caddy2
    ports:
      - "8082:80"
    volumes:
      - $PWD/caddy-conf/cnf-2:/etc/caddy
    networks:
      proxy1:
        ipv4_address: 10.5.0.4
      proxy2:
        ipv4_address: 10.5.1.4
      proxy3:
        ipv4_address: 10.5.2.4

  caddy3:
    image: caddy:latest
    container_name: caddy3
    ports:
      - "8083:80"
    volumes:
      - $PWD/caddy-conf/cnf-3:/etc/caddy
    networks:
      proxy1:
        ipv4_address: 10.5.0.5
      proxy2:
        ipv4_address: 10.5.1.5
      proxy3:
        ipv4_address: 10.5.2.5

networks:
  proxy1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1
  proxy2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.1.0/24
          gateway: 10.5.1.1
  proxy3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.2.0/24
          gateway: 10.5.2.1
